version: "3.7"
services:

  web:
    build: web
    image: osmanirosado/dvdrental-website:2020.03.29
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./web:/home/django/project
    ports:
      - 8096:8000
    user: 1000:1000

  db:
    image: osmanirosado/dvdrental-database:2019.05
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_PORT: 5432

  pgadmin:
    image: dpage/pgadmin4:4.18
    restart: always
    ports:
      - 8098:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ernesto
      PGADMIN_DEFAULT_PASSWORD: example

