version: "3.7"
services:

  web:
    build: web
    image: osmanirosado/dvdrental-adminsite:2020.07.23
    env_file:
      - .env
    volumes:
      - ./web:/home/django/code
    ports:
      - 8096:${DJANGO_PORT}
    user: 1000:1000
    depends_on:
      - db

  db:
    image: osmanirosado/dvdrental-database-django:2019.05
    hostname: ${POSTGRES_HOST}
    ports:
      - 8097:${POSTGRES_PORT}
    env_file:
      - .env
