version: "3.7"
services:

  web:
    build: web
    image: osmanirosado/dvdrental-adminsite:2020.07.23
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./web:/home/django/code
    ports:
      - 8096:8000
    user: 1000:1000
    depends_on:
      - db

  db:
    image: osmanirosado/dvdrental-database-django:2019.05
    restart: always
    ports:
      - 8097:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_PORT: 5432
