# Generated by Django 2.2.11 on 2020-04-08 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dvdrental', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='activebool',
            new_name='active_bool',
        ),
    ]
