# Generated by Django 2.2.11 on 2020-04-11 17:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvdrental', '0002_auto_20200408_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='special_features',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, null=True, size=None),
        ),
    ]
