# Generated by Django 2.2.11 on 2020-04-11 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dvdrental', '0003_auto_20200411_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmactor',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dvdrental.Actor'),
        ),
        migrations.AlterField(
            model_name='filmactor',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dvdrental.Film'),
        ),
    ]
