# Generated by Django 2.2.11 on 2020-04-11 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dvdrental', '0005_auto_20200411_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dvdrental.Customer'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dvdrental.Inventory'),
        ),
    ]
